# -------------------------------------------------------------------------------------
# Media Types
# See: https://gohugo.io/templates/output-formats/#media-types
# -------------------------------------------------------------------------------------

# Options to make output .md files
["text/markdown"]
  suffixes = ["md"]
# Options to make output .txt files
["text/plain"]
  suffixes = ["txt"]
