# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------


#[[main]]
#  identifier = "documentation"
#  name = "Docs"
#  url = "/categories/documentation/"
#  title = "Theme Documentation"
#  weight = 1
#  [main.params]
#    icon = "fa-regular fa-newspaper"



[[main]]
  identifier = "archives"
  parent = ""
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  name = "Archives"
  url = "/archives/"
  # title will be shown when you hover on this menu link
  title = "All My Posts"
  weight = 3
  # FixIt 0.2.14 | NEW add user-defined content to menu items
  [main.params]
    # add css class to a specific menu item
    class = ""
    # whether set as a draft menu item whose function is similar to a draft post/page
    draft = false
    # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
    icon = "fa-solid fa-archive"
    # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
    type = ""


[[main]]
  identifier = "categories"
  parent = ""
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = "Posts Organised by Category"
  weight = 1
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "collections"
  parent = ""
  name = "Collections"
  url = "collections/"
  title = "Multipart Posts"
  weight = 2
  [main.params]
    icon = "fa-solid fa-layer-group"

[[main]]
  identifier = "tags"
  parent = ""
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 5
  [main.params]
    icon = "fa-solid fa-tags"



[[main]]
  identifier = "About"
  parent = ""
  pre = ""
  post = ""
  name = "About"
  url = "https://becos76.github.io"
  title = "About Me"
  weight = 6
  [main.params]
    icon = "fa-solid fa-signature"

#[[main]]
#  identifier = "About2"
#  parent = ""
#  pre = ""
#  post = ""
#  name = "About2"
#  url = "/tags/"
#  title = "About Me2"
#  weight = 5
#  [main.params]
#    icon = "fa-solid fa-heart-circle-bolt text-danger fa-beat"
#    #class = "fa-bounce"