# -------------------------------------------------------------------------------------
# Modules Configure
# See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
# -------------------------------------------------------------------------------------

[[imports]]
  path = "github.com/hugo-fixit/FixIt"

[hugoVersion]
  extended = true
  min = "0.112.0"
