baseURL = 'https://net4fungr.github.io'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Becos :: Blogs'
theme = 'LoveIt'
enableEmoji = true

[params]
  # LoveIt theme version
  version = "0.2.X"
  description = "Becos76 Blog"
  keywords = ["Theme", "Hugo"]
 # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/net4fungr"
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "02-01-2006"
  # website images for Open Graph and Twitter Cards
  images = ["/images/pyrtr.png"]

[params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "search my posts"
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

[params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "images/pyrtr.png"
      # title name
      name = "...sssh and blog..."
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true

[params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ""
       # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2021
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a>'

[params.section]
    # special amount of posts in each section page
    paginate = 10
    # date format (month and day)
    dateFormat = "02-01"
    # amount of RSS pages
    rss = 10

[params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

[params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "images/pyrtr.png"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Bee Blogs"
      # subtitle shown in home page
      subtitle = "Welcome to a Yet Another Blog site!!!<br><h2 style='color:red'>Currently::Under::Construction</h2>CU soon!"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "Views, thoughts, and opinions expressed in this blog belong solely to the author, and not necessarily to the author's employer, organization, commitee or other group or individual."
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 2
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
 
 [params.social]
    GitHub = "becos76"
    Linkedin = "becos"
    Twitter = "mkaliotis"
    Email = "net4fungr@gmail.com"
    RSS = true

[params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = true
    # whether to enable lightgallery
    lightgallery = true
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # LoveIt NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # LoveIt CHANGED | 0.2.0 KaTeX 
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 20
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
    [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        # LoveIt NEW | 0.1.1
        enable = false
        # Disqus shortname to use Disqus in posts
        shortname = ""
      # Gitalk comment config
      [params.page.comment.gitalk]
        # LoveIt NEW | 0.1.1
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # LoveIt NEW | 0.2.6 emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "themes/LoveIt/assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        emoji = ""
 [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "_"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

[params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<b>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = "</b>"
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Click to see my blog posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "<b>"
    post = "</b>"
    name = "Tags"
    url = "/tags/"
    title = "My Tags"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = "<b>"
    post = "</b>"
    name = "Categories"
    url = "/categories/"
    title = "Blog Categories"
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = "<b>"
    post = "</b>"
    name = "About Me"
    url = "http://becos76.github.io"
    title = "Access my Bio"
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "becos"
  email = "net4fungr(at)gmail(dot)com"
  link = "https://becos76.github.io"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  # LoveIt DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  # LoveIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]